---
title: "Visualize Community-based Features"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(ggthemes)


wide_to_long <- function(df, id_var, key_var, val_var, sort_by){
    df %>% 
        t() %>% as.data.frame() %>% 
        rownames_to_column(id_var) %>% 
        arrange(!!sort_by) %>% 
        gather(!!key_var, !!val_var, -(!!id_var)) 
}

```

## community

#### what's the size of each community? Also the top 10 package members?
```{r}
#TODO
```


## function naming convention
```{r, include=FALSE}
df_naming_ratio_total <- readRDS('community_df_naming_ratio_total.RDS')
levels_naming <- c('dotted', 'allupper', 'alllower', 'other', 'upcamel', 'lowcamel', 'snake')
df_naming_ratio_long <- df_naming_ratio_total %>% 
    wide_to_long(id_var = 'community', key_var = 'naming', val_var = 'ratio', sort_by = quo(snake)) %>% 
    mutate(percentage = ratio*100, 
           community=factor(community, levels = unique(community)),
           naming=factor(naming, levels = levels_naming)) 
```

#### overall

```{r naming, echo=FALSE, fig.height = 6, fig.width = 12}
g_naming <- ggplot(aes(y = percentage, x = community, fill = naming), data = df_naming_ratio_long) + 
    geom_bar(stat="identity") + 
    coord_flip() 

g_naming
```

```{r, include=FALSE}
png("visualization_community/naming_among_community.png", width = 9*96, height = 6*96)
g_naming
dev.off()
```

#### within each community
```{r}
gen_fig_naming_dist <- function(target_community){
    df_plot <- df_naming_ratio_long %>% filter(community == target_community)
    g <- ggplot(aes(y = percentage, x = naming, fill=naming), data = df_plot) + 
        geom_bar(stat="identity") + 
        coord_flip() +
        labs(title = target_community) + 
        theme_hc() + theme(legend.position = "none", panel.grid.major.y = element_blank())    
    return(g)
}


communities <- as.character(unique(df_naming_ratio_long$community))
for (comm in communities){
    g <- gen_fig_naming_dist(comm)
    print(g)
    png(sprintf("visualization_community/naming_in_comm_%s.png", comm), width = 2*96, height = 2*96)
    print(g)
    dev.off()
}

```


#### what's most popular naming convention within community?
```{r, echo=FALSE}
idxmax <- function(vals){
    idx <- which(vals == max(vals))
    return(names(vals)[idx])
}
df_pop <- df_naming_ratio_total %>% t() %>% as.data.frame()
df_pop_summary <- data.frame(community = df_pop %>% apply(2, idxmax), ratio = df_pop %>% apply(2, max)) 
df_pop_summary

```



## cake plot: features 

```{r features, echo=FALSE, fig.height = 24, fig.width = 12}
df_ratio_total <- readRDS('community_df_ratio_total.RDS')
levels_feature <- apply(df_ratio_total, 1, max) %>% sort(decreasing = TRUE) %>% names()

df_ratio_long <- df_ratio_total %>% 
    wide_to_long(id_var = 'community', key_var = 'feature', val_var = 'ratio', sort_by = quo(fx_opencurly)) %>% 
    mutate(percentage = ratio*100, 
           community= factor(community, levels = unique(community)),
           feature = factor(feature, levels_feature)) 


g_features <- ggplot(aes(y = percentage, x = community), data = df_ratio_long) + 
    geom_bar(stat="identity", position="dodge") +
    facet_grid(feature ~ ., switch="y") + 
    scale_y_continuous("percentage", position="right") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), strip.text.y=element_text(angle=180))
    # facet_grid(. ~ feature) + 
    # coord_flip()

g_features
```

```{r, include=FALSE}
png("visualization_community/features_among_community.png", width = 10*96, height = 16*96)
g_features
dev.off()
```
